{% set version = "2.0.2" %}

package:
  name: xgems
  version: {{ version }}

source:
  url: https://github.com/gemshub/xgems/archive/v{{ version }}.tar.gz
  sha256: ea43e9e4d1082073cbb0c587026e18579a14c67b5f31b9ca4c1f0adadf8ad6da

build:
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [win]
    - make   # [unix]
    - python  # [win or osx]
    - pip  # [win or osx]
    - setuptools  # [win or osx]
    - wheel  # [win or osx]

  host:
    - python
    - pip
    - setuptools
    - wheel
    - pybind11
    - eigen >=3.4.0
    - spdlog
    - gems3k =>4.4.4
    - thermofun >=0.5.4

  run:
    - python
    - gems3k =>4.4.4
    - thermofun >=0.5.4

test:
  commands:
    - cat ${SRC_DIR}/conda_test_runner.sh  # [unix]
    - test -d ${PREFIX}/include/xGEMS  # [unix]
    - test -f ${PREFIX}/include/xGEMS/ChemicalEngine.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xGEMS\ChemicalEngine.hpp (exit 0) else (exit 1)  # [win]
  imports:
    - xgems  # [win]
    - xgems  # [linux]

about:
  home: https://github.com/gemshub/xgems
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: The next-generation of C++ and Python API for GEMS geochemical modeling tool.
  doc_url: https://github.com/gemshub/xgems
  dev_url: https://github.com/gemshub/xgems

extra:
  recipe-maintainers:
    - gdmiron
    - dimitrikulik
    - sdmytrievs
    - allanleal
