{% set version = "2.0.1" %}

package:
  name: xgems
  version: {{ version }}

source:
  url: https://bitbucket.org/gems4/xgems/get/v{{ version }}.tar.gz
  sha256: 595662ee6834f684f29fecef0e26bb7d8d2c74604fc5d380788fb0ae8916c5ad

  #git_url: https://dmiron@bitbucket.org/gems4/xgems.git
  #git_rev: fix-build

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja  # [win]
    - make  # [unix]
  host:
    - eigen >=3.4.0
    - spdlog >=1.10.0
    - gems3k =>4.3.5
    - thermofun >=0.4.3
    - pybind11
    - python
    - pip
    - setuptools
  run:
    - eigen >=3.4.0
    - spdlog >=1.10.0
    - gems3k =>4.3.5
    - thermofun >=0.4.3
    - python
    - pip

test:
  commands:
    - cat ${SRC_DIR}/conda_test_runner.sh  # [unix]
    - test -d ${PREFIX}/include/xGEMS  # [unix]
    - test -f ${PREFIX}/include/xGEMS/ChemicalEngine.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xGEMS\ChemicalEngine.hpp (exit 0) else (exit 1)  # [win]
  imports:
    - xgems  # [win]
    - xgems  # [linux]

about:
  home: https://bitbucket.org/gems4/xgems
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: The next-generation of C++ and Python API for GEMS geochemical modeling tool.
  doc_url: https://bitbucket.org/gems4/xgems
  dev_url: https://bitbucket.org/gems4/xgems

extra:
  recipe-maintainers:
    - gdmiron
    - dimitrikulik
    - sdmytrievs
