{% set version = "2.1.0" %}

package:
  name: xgems
  version: {{ version }}

source:
  url: https://github.com/gemshub/xgems/archive/v{{ version }}.tar.gz
  sha256: 55c5a77b58687de625b261598375f3ac884edb71b78382de38994554fbfe7381

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [win]
    - make   # [unix]
    - python  # [win or osx]
    - pip  # [win or osx]
    - setuptools  # [win or osx]
    - wheel  # [win or osx]

  host:
    - python
    - pip
    - setuptools
    - wheel
    - pybind11
    - eigen >=3.4.0
    - spdlog
    - gems3k
    - thermofun

  run:
    - python
    - gems3k
    - thermofun

test:
  commands:
    - cat ${SRC_DIR}/conda_test_runner.sh  # [unix]
    - test -d ${PREFIX}/include/xGEMS  # [unix]
    - test -f ${PREFIX}/include/xGEMS/ChemicalEngine.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xGEMS\ChemicalEngine.hpp (exit 0) else (exit 1)  # [win]
  imports:
    - xgems  # [win]
    - xgems  # [linux]

about:
  home: https://github.com/gemshub/xgems
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: The next-generation of C++ and Python API for GEMS geochemical modeling tool.
  doc_url: https://github.com/gemshub/xgems
  dev_url: https://github.com/gemshub/xgems

extra:
  recipe-maintainers:
    - gdmiron
    - dimitrikulik
    - sdmytrievs
    - allanleal
