{% set version = "1.0.7" %}

package:
  name: xgems
  version: {{ version }}

source:
  url: https://bitbucket.org/gems4/xgems/get/v{{ version }}.tar.gz
  sha256: 12f38977fc3758f7b4997b4b39a7cc50b063bd612d41a84df693f251d0e889d4

  #git_url: https://dmiron@bitbucket.org/gems4/xgems.git
  #git_rev: fix-build

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
    - make  # [unix]
  host:
    - gems3k =4.3.3
    - thermofun >=0.4.1
    - pybind11
    - eigen
    - python
  run:
    - python
    - gems3k =4.3.3
    - thermofun >=0.4.1

test:
  commands:
    - test -d ${PREFIX}/include/xGEMS  # [unix]
    - test -f ${PREFIX}/include/xGEMS/ChemicalEngine.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xGEMS\ChemicalEngine.hpp (exit 0) else (exit 1)  # [win]
  imports:
    - xgems

about:
  home: https://bitbucket.org/gems4/xgems
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: The next-generation of C++ and Python API for GEMS geochemical modeling tool.
  doc_url: https://bitbucket.org/gems4/xgems
  dev_url: https://bitbucket.org/gems4/xgems

extra:
  recipe-maintainers:
    - gdmiron
    - dimitrikulik
    - sdmytrievs
