{% set version = "1.0.2" %}

package:
  name: xgems
  version: {{ version }}

source:
  url: https://bitbucket.org/gems4/xgems/get/v{{ version }}.tar.gz
  sha256: 80c73080dde2521ce2f353cfaf8f17a38e3b4372aef82254b74d5c16d9cb4a13

build:
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
    - make  # [unix]
  host:
    - gems3k =4.2.0
    - pybind11
    - eigen
    - python
  run:
    - python

test:
  commands:
    - test -d ${PREFIX}/include/xGEMS  # [unix]
    - test -f ${PREFIX}/include/xGEMS/ChemicalEngine.hpp  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xGEMS\ChemicalEngine.hpp (exit 0) else (exit 1)  # [win]
  imports:
    - xgems

about:
  home: https://bitbucket.org/gems4/xgems
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: The next-generation of C++ and Python API for GEMS geochemical modeling tool.
  doc_url: https://bitbucket.org/gems4/xgems
  dev_url: https://bitbucket.org/gems4/xgems

extra:
  recipe-maintainers:
    - gdmiron
    - dimitrikulik
    - sdmytrievs
